"use strict";

import ErrorStringCompanyName from "./../errors/ErrorStringCompanyName";

class FormattedStringCompanyName {
    private _companyName: string;

    constructor (companyName: string) {
        this.init(companyName);
    }

    private init(companyName: string) : void {
        const e = this.replaceCaracterEspecial(companyName);
        this._companyName = this.replaceTipoEmpresa(` ${ e } `);
    }

    private replaceCaracterEspecial (companyName: string) : string {
        try {
            const caracterEspecial = {
                'À' : 'A',
                'Á' : 'A',
                'Â' : 'A',
                'Ã' : 'A',
                'Ä' : 'A',
                'Å' : 'A',
                'Ă' : 'A',
                'Ā' : 'A',
                'Ą' : 'A',
                'Æ' : 'A',
                'Ǽ' : 'A',
                'à' : 'A',
                'á' : 'A',
                'â' : 'A',
                'ã' : 'A',
                'ä' : 'A',
                'å' : 'A',
                'ă' : 'A',
                'ā' : 'A',
                'ą' : 'A',
                'æ' : 'A',
                'ǽ' : 'A',
                'Þ' : 'B',
                'þ' : 'B',
                'ß' : 'SS',
                'Ç' : 'C',
                'Č' : 'C',
                'Ć' : 'C',
                'Ĉ' : 'C',
                'Ċ' : 'C',
                'ç' : 'C',
                'č' : 'C',
                'ć' : 'C',
                'ĉ' : 'C',
                'ċ' : 'C',
                'Đ' : 'DJ',
                'Ď' : 'D',
                'đ' : 'DJ',
                'È' : 'E',
                'É' : 'E',
                'Ê' : 'E',
                'Ë' : 'E',
                'Ĕ' : 'E',
                'Ē' : 'E',
                'Ę' : 'E',
                'Ė' : 'E',
                'è' : 'E',
                'é' : 'E',
                'ê' : 'E',
                'ë' : 'E',
                'ĕ' : 'E',
                'ē' : 'E',
                'ę' : 'E',
                'ė' : 'E',
                'Ĝ' : 'G',
                'Ğ' : 'G',
                'Ġ' : 'G',
                'Ģ' : 'G',
                'ĝ' : 'G',
                'ğ' : 'G',
                'ġ' : 'G',
                'ģ' : 'G',
                'Ĥ' : 'H',
                'Ħ' : 'H',
                'ĥ' : 'H',
                'ħ' : 'H',
                'Ì' : 'I',
                'Í' : 'I',
                'Î' : 'I',
                'Ï' : 'I',
                'İ' : 'I',
                'Ĩ' : 'I',
                'Ī' : 'I',
                'Ĭ' : 'I',
                'Į' : 'I',
                'ì' : 'I',
                'í' : 'I',
                'î' : 'I',
                'ï' : 'I',
                'į' : 'I',
                'ĩ' : 'I',
                'ī' : 'I',
                'ĭ' : 'I',
                'ı' : 'I',
                'Ĵ' : 'J',
                'ĵ' : 'J',
                'Ķ' : 'K',
                'ķ' : 'K',
                'ĸ' : 'K',
                'Ĺ' : 'L',
                'Ļ' : 'L',
                'Ľ' : 'L',
                'Ŀ' : 'L',
                'Ł' : 'L',
                'ĺ' : 'L',
                'ļ' : 'L',
                'ľ' : 'L',
                'ŀ' : 'L',
                'ł' : 'L',
                'Ñ' : 'N',
                'Ń' : 'N',
                'Ň' : 'N',
                'Ņ' : 'N',
                'Ŋ' : 'N',
                'ñ' : 'N',
                'ń' : 'N',
                'ň' : 'N',
                'ņ' : 'N',
                'ŋ' : 'N',
                'ŉ' : 'N',
                'Ò' : 'O',
                'Ó' : 'O',
                'Ô' : 'O',
                'Õ' : 'O',
                'Ö' : 'O',
                'Ø' : 'O',
                'Ō' : 'O',
                'Ŏ' : 'O',
                'Ő' : 'O',
                'Œ' : 'O',
                'ò' : 'O',
                'ó' : 'O',
                'ô' : 'O',
                'õ' : 'O',
                'ö' : 'O',
                'ø' : 'O',
                'ō' : 'O',
                'ŏ' : 'O',
                'ő' : 'O',
                'œ' : 'O',
                'ð' : 'O',
                'Ŕ' : 'R',
                'Ř' : 'R',
                'ŕ' : 'R',
                'ř' : 'R',
                'ŗ' : 'R',
                'Š' : 'S',
                'Ŝ' : 'S',
                'Ś' : 'S',
                'Ş' : 'S',
                'š' : 'S',
                'ŝ' : 'S',
                'ś' : 'S',
                'ş' : 'S',
                'Ŧ' : 'T',
                'Ţ' : 'T',
                'Ť' : 'T',
                'ŧ' : 'T',
                'ţ' : 'T',
                'ť' : 'T',
                'Ù' : 'U',
                'Ú' : 'U',
                'Û' : 'U',
                'Ü' : 'U',
                'Ũ' : 'U',
                'Ū' : 'U',
                'Ŭ' : 'U',
                'Ů' : 'U',
                'Ű' : 'U',
                'Ų' : 'U',
                'ù' : 'U',
                'ú' : 'U',
                'û' : 'U',
                'ü' : 'U',
                'ũ' : 'U',
                'ū' : 'U',
                'ŭ' : 'U',
                'ů' : 'U',
                'ű' : 'U',
                'ų' : 'U',
                'Ŵ' : 'W',
                'Ẁ' : 'W',
                'Ẃ' : 'W',
                'Ẅ' : 'W',
                'ŵ' : 'W',
                'ẁ' : 'W',
                'ẃ' : 'W',
                'ẅ' : 'W',
                'Ý' : 'Y',
                'Ÿ' : 'Y',
                'Ŷ' : 'Y',
                'ý' : 'Y',
                'ÿ' : 'Y',
                'ŷ' : 'Y',
                'Ž' : 'Z',
                'Ź' : 'Z',
                'Ż' : 'Z',
                'ž' : 'Z',
                'ź' : 'Z',
                'ż' : 'Z'
            }

            for (const [chave, valor] of Object.entries(caracterEspecial)) {
                const replace = chave;
                // Faz um regex que encontra o caracter especial na string
                const re = new RegExp(replace, "g");
                // substitui o caracter especial pelo caracter utf-8
                companyName = companyName.toUpperCase().replace(re, valor);
            }

            return companyName.trim();
        } catch (err) {
            throw new ErrorStringCompanyName(err);
        }
    }

    private replaceTipoEmpresa(companyName : string) : string {
        try {
            const sigla: string[] = [
                " A.G ",
                " AG. ",
                " AG ",
                " BVBA. ",
                " BVBA ",
                " B.V.B.A. ",
                " B.V.B.A ",
                " B.V ",
                " B.V. ",
                " BV. ",
                " BV ",
                " CO. ",
                " CORPORATION. ",
                " CORPORATION ",
                " D.A. ",
                " D.A ",
                " DA. ",
                " GMBH & CO. KG ",
                " GMBH & CO. ",
                " GMBH & CO ",
                " GMBH ",
                " INC. ",
                " INC ",
                " LLC. ",
                " LLC ",
                " LLP. ",
                " LLP ",
                " LP. ",
                " LP ",
                " N.V. ",
                " N.V ",
                " NV.",
                " NV ",
                " PLC. ",
                " PLC ",
                " S.A. de C.V. ",
                " S/A de C.V. ",
                " S.A.B de C.V. ",
                " S.A.B de C.V ",
                " S.P.A. ",
                " S.P.A ",
                " SRL. ",
                " SRL ",
                " S.À.R.L. ",
                " S.À.R.L ",
                " S.A.R.L. ",
                " S.A.R.L ",
                " S.A.C.I.F. Y A. ",
                " S.A.I.C. Y F. ",
                " SAIC Y F ",
                " SAICYF ",
                " S.A.T.A.C E I. ",
                " SATAC E I ",
                " SATACEI ",
                " S A I C Y F ",
                " S A Q E I ",
                " S.A.Q. E I. ",
                " SAQEI. ",
                " SAQEI ",
                " S.A. U.T.E. ",
                " S.A. - U.T.E. ",
                " SA UTE ",
                " SAUTE ",
                " S.E.M. ",
                " SEM. ",
                " SEM ",
                " S E M ",
                " SACIF Y A ",
                " SACIFYA ",
                " S.A.C.I. ",
                " S A C I ",
                " S.A.R.L. ",
                " SGPS. ",
                " S.A.C.E.I. ",
                " S.A.C. E I. ",
                " SAC E I ",
                " SACEI ",
                " S.C.A. ",
                " SCA. ",
                " SCA ",
                " M.E.I ",
                " MEI. ",
                " MEI ",
                " EIRELI. ",
                " EIRELI ",
                " LTDA. ",
                " LTDA ",
                " LTD. ",
                " LTD ",
                " SAU ",
                " S.A.U. ",
                " S.A. ",
                " S.A ",
                " S/A. ",
                " S/A ",
                " EPP. ",
                " EPP ",
                " S/S. ",
                " S/S ",
                " S.S. ",
                " S.S ",
                " S.C. ",
                " S.C ",
                " S/C. ",
                " S/C ",
                " ME. ",
                " EI. ",
                " DTVM. ",
                " C.T.V.M. ",
                " C.T.V.M ",
                " CTVM. ",
                " CTVM ",
                " A.S. ",
                " A.S ",
                " A.G. ",
                " AG. ",
                " AG ",
                " S.R.L. ",
                " S.R.L ",
                " SRL "
            ];

            // ----- Verifica-se se no nome da empresa tem a sigla encontrada
            // ----- nessa posição no array
            for (const s of sigla) {
                if (companyName.toUpperCase().indexOf(s) !== -1) {
                    companyName = companyName.toUpperCase().replace(s, ' ');
                }
            }

            return companyName.trim();
        } catch (err) {
            throw new ErrorStringCompanyName(err);
        }
    }

    public get empresa() : string {
        return this._companyName.trim();
    }

}

export default FormattedStringCompanyName;